# Funding links (optional). Leaving these empty is fine.
# Fill in when you’re ready — do not add placeholders that imply active funding.

github: []
patreon: []
open_collective: []
ko_fi: []
liberapay: []
issuehunt: []
otechie: []
custom: []
