import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { FileText, Scale, Shield, AlertTriangle } from 'lucide-react';
import { combineSchemas, generateBreadcrumbSchema } from '../lib/seo';
import { applyPageMetadata } from '../components/seo/applyPageMetadata';

export const TermsOfServicePage: React.FC = () => {
  const schema = combineSchemas(
    generateBreadcrumbSchema(
      [
        { name: 'Home', url: '/' },
        { name: 'Terms of Service', url: '/terms' },
      ],
      { siteUrl: 'https://www.paintracker.ca' }
    )
  );

  useEffect(() => {
    return applyPageMetadata({
      title: 'Terms of Service — Pain Tracker',
      description:
        'Terms of Service for Pain Tracker, including local-first usage boundaries, export responsibilities, and WorkSafeBC documentation disclaimers.',
      canonicalUrl: 'https://www.paintracker.ca/terms',
    });
  }, []);

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-950 via-slate-900 to-slate-950 text-white">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: schema }} />

      <a
        href="#main-content"
        className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-50 focus:px-4 focus:py-2 focus:bg-white focus:text-slate-900 focus:rounded-md"
      >
        Skip to main content
      </a>

      <main id="main-content" role="main" className="max-w-3xl mx-auto px-6 py-16">
        <header className="text-center mb-12">
          <div className="flex justify-center mb-4">
            <Scale className="h-12 w-12 text-cyan-400" aria-hidden="true" />
          </div>
          <h1 className="text-4xl md:text-5xl font-bold mb-4 bg-gradient-to-r from-cyan-400 to-emerald-400 bg-clip-text text-transparent">
            Terms of Service
          </h1>
          <p className="text-lg text-slate-300">Pain Tracker by CrisisCore Systems</p>
          <p className="text-sm text-slate-500 mt-2">Effective: May 2026 · Version 1.0</p>
        </header>

        <section className="mb-10 p-6 rounded-xl bg-slate-800/60 border border-cyan-500/20" aria-labelledby="acceptance">
          <h2 id="acceptance" className="text-xl font-bold mb-3 text-cyan-300 flex items-center gap-2">
            <FileText className="h-5 w-5" aria-hidden="true" />
            Acceptance and scope
          </h2>
          <p className="text-slate-300 leading-relaxed">
            By using Pain Tracker, you agree to these Terms. Pain Tracker is provided as a local-first software tool
            for personal symptom documentation, trend review, and user-controlled export.
          </p>
        </section>

        <section className="mb-10" aria-labelledby="not-medical-legal-advice">
          <h2 id="not-medical-legal-advice" className="text-2xl font-bold mb-4 text-white">
            Not medical or legal advice
          </h2>
          <div className="space-y-3 text-slate-300">
            <p>
              Pain Tracker is not a medical device and does not provide diagnosis, treatment, or emergency guidance.
            </p>
            <p>
              Pain Tracker is also not a law firm or legal representative. Documentation generated by the app,
              including WorkSafeBC-oriented exports, is informational only and does not guarantee claim acceptance,
              entitlement, adjudication outcome, or legal sufficiency.
            </p>
          </div>
        </section>

        <section className="mb-10" aria-labelledby="worksafebc-use-case">
          <h2 id="worksafebc-use-case" className="text-2xl font-bold mb-4 text-white">
            WorkSafeBC and claims documentation use case
          </h2>
          <div className="rounded-lg border border-amber-500/30 bg-amber-500/10 p-4 text-sm text-slate-200">
            <p>
              Export templates and PDF summaries are intended to help you organize your own records for clinicians,
              case managers, and claims conversations. They do not replace professional medical assessments,
              adjudicator requirements, legal advice, or official forms.
            </p>
          </div>
          <ul className="mt-4 space-y-2 text-slate-300">
            <li>• You are responsible for reviewing export accuracy before sharing.</li>
            <li>• You choose whether, when, and with whom to share exported files.</li>
            <li>• You are responsible for secure handling of files after export.</li>
          </ul>
        </section>

        <section className="mb-10" aria-labelledby="local-first-boundary">
          <h2 id="local-first-boundary" className="text-2xl font-bold mb-4 text-white">
            Local-first boundary and data responsibility
          </h2>
          <p className="text-slate-300 mb-3">
            Core records are designed to stay on your device by default. You are responsible for maintaining access to
            your own device, browser storage, and backups.
          </p>
          <p className="text-slate-300">
            If you clear browser data, lose your device, lose backup files, or forget credentials, records may be
            permanently unavailable.
          </p>
        </section>

        <section className="mb-10" aria-labelledby="acceptable-use">
          <h2 id="acceptable-use" className="text-2xl font-bold mb-4 text-white">
            Acceptable use
          </h2>
          <ul className="space-y-2 text-slate-300">
            <li>• Do not use Pain Tracker to violate laws or rights of others.</li>
            <li>• Do not attempt to interfere with service integrity or security controls.</li>
            <li>• Do not misrepresent generated exports as third-party authored records.</li>
          </ul>
        </section>

        <section className="mb-10" aria-labelledby="warranty-liability">
          <h2 id="warranty-liability" className="text-2xl font-bold mb-4 text-white">
            Warranty and liability limits
          </h2>
          <p className="text-slate-300">
            Pain Tracker is provided on an "as is" and "as available" basis to the maximum extent permitted by law.
            We do not warrant uninterrupted availability, error-free operation, or fitness for a particular legal or
            clinical outcome.
          </p>
        </section>

        <section className="mb-10 p-6 rounded-xl bg-red-500/10 border border-red-500/20" aria-labelledby="emergency">
          <h2 id="emergency" className="text-xl font-bold mb-3 text-red-300 flex items-center gap-2">
            <AlertTriangle className="h-5 w-5" aria-hidden="true" />
            Emergency notice
          </h2>
          <p className="text-slate-200">
            Pain Tracker is not an emergency service. If you are in immediate danger or experiencing a medical
            emergency, call local emergency services right away.
          </p>
        </section>

        <section className="mb-12" aria-labelledby="changes-contact">
          <h2 id="changes-contact" className="text-2xl font-bold mb-4 text-white flex items-center gap-2">
            <Shield className="h-5 w-5 text-cyan-300" aria-hidden="true" />
            Changes and contact
          </h2>
          <p className="text-slate-300 mb-3">
            We may update these Terms over time. Continued use after updates means you accept the revised Terms.
          </p>
          <p className="text-slate-400 text-sm">
            Questions: use the project issue tracker or security policy links in the{' '}
            <Link to="/privacy" className="text-cyan-400 hover:text-cyan-300 underline">
              Privacy Policy
            </Link>
            .
          </p>
        </section>

        <div className="text-center">
          <Link to="/" className="text-slate-400 hover:text-white transition-colors">
            ← Back to home
          </Link>
        </div>
      </main>
    </div>
  );
};
