name: mutation

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 6 * * 1' # Weekly Monday 06:00 UTC

jobs:
  stryker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci --legacy-peer-deps --omit=optional || echo "npm ci failed, continuing with npx"
      - name: Run Stryker (phase 1)
        run: npx -y @stryker-mutator/core@8.2.0 run || true
      - name: Generate mutation badge
        run: node scripts/generate-mutation-badge.mjs
      - name: Commit badge
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull --rebase
          git add badges/mutation-badge.json
          git commit -m "ci(mutation): update mutation badge [skip ci]" || echo "No changes"
          git push
      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: mutation-report
          path: reports/mutation/**
