name: Mutation check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  mutation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run focused Stryker (non-blocking)
        run: |
          npx stryker run stryker.conf.cjs --logLevel info || true

      - name: Upload mutation report
        uses: actions/upload-artifact@v4
        with:
          name: mutation-report
          path: reports/mutation

      - name: Post summary comment (optional)
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const summary = 'Mutation testing run completed. Artifact `mutation-report` uploaded.';
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: summary
            });
